### ISSUE TITLE
[BUG] Tantárgy szerinti rendezés

### ISSUE THREAD

**Issue by somlaiadam** [filcnaplo/filcnaplo#100]
KLIKK-es iskolánál a jegyek rendezése tantárgy szerint nem működik, véletlenszerűen csoportosítja a jegyeket, egy tantárgy többször is szerepel.
PL.: Irodalom
A statisztika fülön viszont jól rakja a jegyeket a tárgyakhoz.
![Screenshot_20200327-120114_Photos](https://user-images.githubusercontent.com/18148149/77750319-d51f8380-7023-11ea-92e9-475c9cec7c65.jpg)

**Comment by palmarci** [comment]
szép kis 100. bug, gratu

**Comment by UnknownPlayer78** [comment]
@somlaiadam nálam is ugyanez a probléma

**Comment by RedyAu** [comment]
Elég furcsa ez az egész, szintén klikes sulival nekem teljesen jó..

**Comment by palmarci** [comment]
légyszi írjátok le, hogy melyik kréta szerveren vagytok (pingeljétek meg azt a subdomaint, amelyiken van a webes enaplótok és írjátok ki pl.: 2-nszfh.ekreta.hu)

**Comment by somlaiadam** [comment]
2-kaffee.e-kreta.hu

**Comment by thegergo02** [comment]
2-kaffe: nekem is rossz

**Comment by RedyAu** [comment]
Öhm... 2-kaffee: Nekem jó :D

**Comment by ssk73** [comment]
2-azure

(nem KLIKK, de hátha hasznos)

**Comment by Zoldszemesostoros** [comment]
Nekem is megy a 2-kaffee szerveren

**Comment by RedyAu** [comment]
@Zoldszemesostoros Ez tantárgyfelviteltől függ, jegyexportot kéne invesztigálni

**Comment by somlaiadam** [comment]
@RedyAu Ez volt szembetűnő különbség:
A felső a KLIKKes sulis, alsós a saját centrumos.
A KLIKKes suliban a Subject és a SubjectCategoryName eltér.
![received_1975857505879434](https://user-images.githubusercontent.com/18148149/77962945-d0392900-72dc-11ea-9f5d-eb12dae40838.png)

**Comment by RedyAu** [comment]
Ez sem ettől függ. Nekem is mások a kategóriák és mégis jó a rendezés.
