### ISSUE TITLE
[BUG] Codemagic 404

### ISSUE THREAD

**Issue by Zoldszemesostoros** [filcnaplo/filcnaplo#103]
Ha a codemagic badgera kattintok, egy "Not found" üzenet fogad.
[screenshot](https://user-images.githubusercontent.com/42379455/77939915-247de200-72b8-11ea-9141-7f7bed380112.png)

**Comment by UnknownPlayer78** [comment]
A codemagic-hez csak team tagoknak van hozzáférésük, csak dísznek van kint.
