### ISSUE TITLE
[Feature Request] Mellékletek támogatása

### ISSUE THREAD

**Issue by Luger67** [filcnaplo/filcnaplo#105]
Az üzenet menüpontnál a becsatolt mellékletet nem találom, nincs. Más appban látom, hogy van.

**Comment by UnknownPlayer78** [comment]
A Filc Napló jelenleg nem támgoatja a mellékleteket. Egy későbbi frissítésben ez is bekerülhet.

**Comment by Luger67** [comment]
Kösz, csak most az van, hogy minden tanár a feladatokat, az üzenet mellékleteként küldi el.

________________________________

**Comment by RedyAu** [comment]
Teljesen érthető, de ez egy nagyobb feature ami nyomokban sem létezik a Filcben. Amint tudjuk, hozzáadjuk, addig is vissza-vissza kell térned a Sötét Oldalra ;)

**Comment by UnknownPlayer78** [comment]
kész

**Comment by Luger67** [comment]
Most  a ma reggeli frissítés után (igaz előtte is volt már probléma) az üzenetek egyáltalán nem jelennek meg.
Három telefonon is próbáltam Android 9 és 10 alatt.
Elsőre, amikor először indul az alkalmazás akkor igen, de utána hiába zárom be az alkalmazást, csak akkor fog működni újból egy alkalommal, ha törlöm az adatokat.
És újból … és újból … (most egyszer a sok próbálkozás után percek múlva bejött)

Ha az üzenetek mellékletének letöltésre kattintok, automatikusan menti.
Esetleg megoldható lenne, hogy megkérdezi mit szeretnék, mondjuk egyből megnyitni valamivel.
Köszönöm

Feladó: UnknownPlayer78<mailto:notifications@github.com>
Elküldve: 2020. április 3., péntek 20:30
Címzett: filcnaplo/filcnaplo<mailto:filcnaplo@noreply.github.com>
Másolatot kap: Luger67<mailto:luger27@hotmail.hu>; Author<mailto:author@noreply.github.com>
Tárgy: Re: [filcnaplo/filcnaplo] [Feature Request] Mellékletek támogatása (#105)


Jelenleg nincs, viszont dologzunk rajta.
