### ISSUE TITLE
[BUG] Első indítás után nem működik az app

### ISSUE THREAD

**Issue by Kristof120701** [filcnaplo/filcnaplo#106]
Miután adatok törlését nyomok az appra és bejelentkezek, akkor működik, de amint manuálisan lefrissítem a főoldalt vagy bezárom és újraindítom a filcet, nem működik többet, csak ha megint resetelem az appot.

![Screenshot_20200401-151259_Filc_Napl�](https://user-images.githubusercontent.com/54689523/78247162-af462300-74ea-11ea-8fd9-50e168cb1242.png)

**Comment by RedyAu** [comment]
Ez azóta van így, mióta ezt a piros üzenetet is megkapod?

**Comment by Kristof120701** [comment]
Azt hiszem igen. On Apr 2, 2020 17:46, RedyAu <notifications@github.com> wrote:

Ez azóta van így, mióta ezt a piros üzenetet is megkapod?

**Comment by RedyAu** [comment]
Kérlek pingeld meg iskolád kréta elérését a konzolban (az iskolalistánál látod az iskoládhoz tartozó url-t), és írd meg melyik szerver szolgál ki. Az enyém pl:
![image](https://user-images.githubusercontent.com/12989935/78275466-f09df900-7511-11ea-8037-de45c9f59fe3.png)

**Comment by Kristof120701** [comment]
![image](https://user-images.githubusercontent.com/54689523/78282336-660ec700-751c-11ea-80d2-b98c17cefde6.png)
