### ISSUE TITLE
[BUG] osztályátlag

### ISSUE THREAD

**Issue by ssk73** [filcnaplo/filcnaplo#112]
Minden tantárgynál rossz az osztályátlag, csak kaomojit dob.

2-azure, krg

**Comment by RedyAu** [comment]
@ssk73 Sajnos sok szerveren nem elérhető az osztályátlag, de nálam például ok. Esetleg lehet, hogy jobb lenne ha nem kaomoji lenne, hanem ha nem kap osztályátlagot, akkor ott sincs a helye.

**Comment by ssk73** [comment]
@RedyAu Persze, a lényeg az hogy szebben legyen megoldva

**Comment by thegergo02** [comment]
@RedyAu Mi nem tudnánk kiszámolni ez esetben? Hisz a weight meg hogy beleszámít -e az átlagba is megvan

**Comment by thegergo02** [comment]
@thegergo02 Azt hittem saját, akkor semmi

**Comment by RedyAu** [comment]
Az osztályátlagok hiányoznak az Ami-s api összesített és külön átlagokra szóló lekéréséből is sajnos. Api v3-ig nem kerülnek vissza az appba.
