### ISSUE TITLE
Nem frissít

### ISSUE THREAD

**Issue by Simko75** [filcnaplo/filcnaplo#113]
Üdv! Március 3 óta nem frissülnek a beírt értékelések, de az üzenetek, feljegyzesek sem érkeznek meg. Remélem, lehet orvosolni ezt a problémát hamar, mert egyébbként nagyon kedvelem ezt az alkalmazást :)

**Comment by LetsUpdate** [comment]
Hányas verziót használod?
(A beállítások képernyő alján láthatod)

**Comment by Simko75** [comment]
A legfrissebbet, 1.5.0 :)

**Comment by LetsUpdate** [comment]
Az eredeti kréta allkalmazásban megjelennek?

**Comment by Simko75** [comment]
Igen, onnan tudom, hogy jönnek az értékelések és feljegyzések is, de a Filcben nem jelennek meg sajnos. Az órarend az rendben van, hibátlan, pontos. Minden más viszont 3-tól megszűnt. Elvégeztem a "szokásos" teendőket. App le, mobil újraindit, app újból telepítés, de semmi nem változott.

**Comment by thegergo02** [comment]
@Simko75 Elég furcsa, az AMIs lekérdezéseket használjuk már ugye?

**Comment by LetsUpdate** [comment]
Nemtudom hogy 3 nappal ezelött is ez volt e a hiba, de most néztem, hogy az eredeti app sem tudja rekérni a lekérdezéshez szükséges adatokat.
A szokásos json helyet a szerver egy html-oldalt ad vissza 403-as hibával...
a krétánál szúrták el...

**Comment by Simko75** [comment]
3-ig még rendben működött. Kipróbáltam azóta az Ariszto-t is, az rendesen, hiánytalanul bead mindent, de a Filc továbbra is néma

**Comment by LetsUpdate** [comment]
Én már az eredeti alkalmazásba be se tudok belépni....

**Comment by LetsUpdate** [comment]
@Simko75 A hiba még fent áll nálad?

**Comment by Simko75** [comment]
Igen, a helyzet változatlan. 04.03-tól a napló frissítése "megszűnt létezni" :)

**Comment by Simko75** [comment]
Mostanra viszont már rendbe jött. Nagyon nehezen, kb 1 percig is eltartott mire elindult, de hiánytalanul mindent megjelenít, amit eddig nem tudott valami miatt. :)

**Comment by Zoldszemesostoros** [comment]
Nekem is előjött, újra kellett teepíteni.
Huawei telefon, 2-kaffee szerver.

**Comment by Zoldszemesostoros** [comment]
Most frissít, végre lejjebb csúszott az órai aktivitás karó.

**Comment by thegergo02** [comment]
@Zoldszemesostoros nekem is ment ma

**Comment by Zoldszemesostoros** [comment]
Szerintem a krétások rontottak el valamit: a hivatalos appban a főoldalon megjelennek az új jegyek, de az értékeléseknél nem.

**Comment by Simko75** [comment]
Nálam az is hibátlanul működik, de itt a Filcnél még mindig nem

**Comment by RedyAu** [comment]
1.5.1, 1.5.2, és 1.5.3-ban javítva.

**Comment by RedyAu** [comment]
Mégsincs javítva úgy tűnik, 1.5.3-ról is több review jött hogy nem frissít, vagy hogy csak első telepítéskor és utána nem. Nem tudom, mit lehetne (vagy mit fogunk) vele kezdeni, de azért újranyitom ¯\_(ツ)_/¯

**Comment by RedyAu** [comment]
Ok, megvan a gond. 1.5.1-es frissítés adatstruktúra-módosítása még mindig sok embernél gondot okoz, 1.5.4-ben lesz adatbázis-törlésre lehetőség.
