### ISSUE TITLE
[BUG] Ismeretlen (maybe) szerver hiba

### ISSUE THREAD

**Issue by cicomk** [filcnaplo/filcnaplo#115]
Több napja Unexpected character hibaüzenetet dobja fel az alkalmazás induláskor.

**Comment by LetsUpdate** [comment]
Az eredeti app sem tudja lekérni a lekérdezéshez szükséges adatokat
a szokásos json helyet a szerver egy html-oldalt ad vissza 403-as hibával...
a krétánál szúrták el...

**Comment by cicomk** [comment]
Állami cégtől mit is vártunk...

**Comment by RedyAu** [comment]
AMI-s apira átálltunk, ezt zárom.
