### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Balint20** [filcnaplo/filcnaplo#117]
Nem frissiti a jegyeket

**Comment by thegergo02** [comment]
Tudjuk, próbálj egy reinstall.
Valakinek az se jó.

**Comment by thegergo02** [comment]
#113 duplicate

**Comment by Balint20** [comment]
Sokszor frissitettem és telepitettem újra de nem jó

Vári Gergő <notifications@github.com> ezt írta (időpont: 2020. ápr. 15.,
Sze 22:17):

**Comment by Simko75** [comment]
Az a baj, hogy már újratelepítettem 2X, de akkor is csak annyi történt, hogy a pillanatnyi állapotot jelenítette meg, továbbra sem frissített utána.

**Comment by Balint20** [comment]
Igen

Simko75 <notifications@github.com> ezt írta (időpont: 2020. ápr. 16., Csü
7:25):

**Comment by thegergo02** [comment]
btw #113 ennek az issuenak, zárolom, nyugodtan írjatok oda ha valami fejlemény van ezzel

**Comment by Balint20** [comment]
Javítsák már meg.

Vári Gergő <notifications@github.com> ezt írta (időpont: 2020. ápr. 17.,
Pén 15:31):
