### ISSUE TITLE
[BUG] Osztályzatnál a nevek nem férnek ki

### ISSUE THREAD

**Issue by csoni1970** [filcnaplo/filcnaplo#118]
Főoldalon az osztályzatoknál a tanuló neve nem mindig látszik, ha hosszú az ok amiért a jegyet kapta. pl. rajz gyakorlati feladat Kiripolsz.         és a többi nem látszik. Két gyereknél kellemetlen. köszi

**Comment by RedyAu** [comment]
Ennek a javításához a jegykártya újradizájnolására lenne szükség, amit az újraírt appban fogunk megtenni. Addig is érdemes lehet a fiókok képernyőn más-más színt beállítani a fiókoknak, így is megkülönböztetve őket.
