### ISSUE TITLE
"Ha kapnék egy..." probléma; félévi jegyek külön menüpont

### ISSUE THREAD

**Issue by Kristof120701** [filcnaplo/filcnaplo#12]
A jegyek tárgyanként résznél rossz helyen van a plusz gomb, mert nem tudom utána a kiválasztott jegyet kitörölni. (jelen esetben az egyes) 

![Screenshot_2020-02-02-23-55-32-047_hu filcnaplo ellenorzo1](https://user-images.githubusercontent.com/54689523/73616922-88b65980-4619-11ea-8559-a4335822e57d.jpg)

Félévi jegyek külön menüpont:
Jobb lenne, ha a félévi jegyeknek lenne egy külön menüpontja valahol az alkalmazásban, ne csak a főoldalon, visszagörgetve.

**Comment by RedyAu** [comment]
Mindkettő javítva van a legfrissebb commitokban, tarts ki a következő updateig ;)

**Comment by RedyAu** [comment]
https://github.com/filcnaplo/filcnaplo/commit/9a080540d0b931a0e1428cc24ead26e6c8218412
![](https://i.imgur.com/gZMpv2e.jpg)
![](https://i.imgur.com/xf1fKxi.jpg)
