### ISSUE TITLE
[BUG] Ha egyik diák az órához házit rögzít, a tanár által kiadott házi eltűnik.

### ISSUE THREAD

**Issue by Vtas1** [filcnaplo/filcnaplo#120]
**Verzió:** 1.5.0. (tehát nem béta)
**Platform:** Android 5.1.0
**Reprodukálás:** A Filc Naplóval vagy a Kréta webes felületén házi feladat hozzáadása az órához. 
**Probléma:** Ezután a Filc Naplóban csak a diák által hozzáadott házi feladat(ok) láthatók (img0). A Kréta felületén mindegyik látszik (img1). Ha több diák is rögzít házit vagy egy diák több házit, akkor is csak a tanár által feladott nem látszik (img2, img3).
![img0](https://user-images.githubusercontent.com/45075899/79837744-3ed84680-83b2-11ea-938f-8752ba953d2a.png)
![img1](https://user-images.githubusercontent.com/45075899/79837763-4566be00-83b2-11ea-851e-986752b1a9da.png)
![img2](https://user-images.githubusercontent.com/45075899/79837780-4ac40880-83b2-11ea-9aae-94df05923395.png)
![img3](https://user-images.githubusercontent.com/45075899/79837793-51528000-83b2-11ea-88fc-1597859e4357.png)

**Rövid összefoglalás:** ha n diák m házit rögzít, akkor a tanár által feladott nem látszik a Filc Naplóban, de a Kréta internetes felületén igen(n, m > 0).

**Comment by Vtas1** [comment]
A homework részben sem jelenik meg az eredeti hf.
![IMG_20200421_094040](https://user-images.githubusercontent.com/45075899/79839052-41d43680-83b4-11ea-8208-e36182260c44.png)
![IMG_20200421_094220](https://user-images.githubusercontent.com/45075899/79839174-6e884e00-83b4-11ea-8143-be877c8709c9.png)
Hétfőn angol előbb van, mint francia.

**Comment by RedyAu** [comment]
Köszönjük a részletes bejelentést!

**Comment by RedyAu** [comment]
Csak az újraírt appban fogjuk javítani, mert át kellene miatta dolgozni egy csomó mindent.
