### ISSUE TITLE
[Feature Request] "Lekérés Kréta appként" és nyelvválasztás kapcsoló legyen elérhető a bejelentkezéskor

### ISSUE THREAD

**Issue by RedyAu** [filcnaplo/filcnaplo#122]
Scaffold iconbutton "Settings" ami popupot nyit ezzel a két beállítással

**Comment by RedyAu** [comment]
![image](https://user-images.githubusercontent.com/12989935/82460314-4d9d4080-9ab9-11ea-88c9-06c9bc23bec4.png)

**Comment by thegergo02** [comment]
@RedyAu kell még a kréta appként gomb?

**Comment by RedyAu** [comment]
Nem tesszük kötelezővé az illegalitást ;)
