### ISSUE TITLE
[Feature Request] Visszaszámláló

### ISSUE THREAD

**Issue by opekope2** [filcnaplo/filcnaplo#125]
Az ötletem egy visszaszámláló egy szünetig vagy egy dátumig, naponként, tantárgyanként, tanáronként, (termenként) lebontva. A flutterhez nem értek, de Kotlinban Androidra már írtam egyet.

**Comment by RedyAu** [comment]
Tudsz írni hozzá egy használati esetet, amikor egy ilyen jól jönne?
Az issuet zárom, mert ez már csak az újraírt appba fog bekerülni, ha valahova.
