### ISSUE TITLE
[BUG] Bejelentkezési hiba

### ISSUE THREAD

**Issue by boti14** [filcnaplo/filcnaplo#130]
Helló. Próbáltam bejelentkezni de azt írja ki hogy (nem sikerült lekérni a Kréta iskolát). Ráadásul a listában nem jelennek meg az iskolák.! Ez miért lehet.?

Adatok:
Android:5.1.1
Modellszám:VF-1397
Kernel ver.: android@tabletbuild2 #1

**Comment by daaniiieel** [comment]
Rajta vagyunk, a szerverünkön van a hiba forrása.

**Comment by hubabuba100** [comment]
Rendben, köszi a választ!
