### ISSUE TITLE
[BUG] Random string UA implementálása

### ISSUE THREAD

**Issue by hubabuba100** [filcnaplo/filcnaplo#131]
Sziasztok!

Azt vettem észre hogy a kliensem nem jeleníti meg a jegyeimet és a bejegyzéseimet május 11. óta. Krétások elkezdték blokkolni az alkalmazást vagy nálam van a probléma?

Adatok:
Filc verzió: 1.1
Android 10
Huawei P Smart 2019

Köszönöm előre a válaszokat!

**Comment by RedyAu** [comment]
A hibát szerveroldalon ideiglenesen javítottuk, stabilabb javítás érkezik a következő verzióban.

**Comment by RedyAu** [comment]
@hubabuba100 Egyébként az 1.1-es Filc verzió már nagyon régi, azzal nem fog működni már egyáltalán. Telepítsd a filcnaplo.hu/download oldalról vagy Playről a legújabb verziót.

**Comment by RedyAu** [comment]
31c4ece
