### ISSUE TITLE
[TOP] In-app frissítés

### ISSUE THREAD

**Issue by palmarci** [filcnaplo/filcnaplo#14]
+ Figyelmeztessen, ha rég volt szerveren frissítés
(edit: Ez továbbra se tudom, mit akar jelenteni, de azért maradjon)

**Comment by RedyAu** [comment]
https://github.com/filcnaplo/filcnaplo/commit/a96a684016fe50741a6ca5547c549cd5a410b12f
https://github.com/filcnaplo/filcnaplo/commit/f387667d123fb9ec9195124e2112c1e30ce330c4
