### ISSUE TITLE
Inkonzisztens "capital()" használat

### ISSUE THREAD

**Issue by RedyAu** [filcnaplo/filcnaplo#15]
Az app van, ahol kapitalizál, van ahol nem. (A függvény az első betűt kapitalizálja, a többit viszont egységesen kicsivé teszi)
Pl. bottomsheet címekben, jegy-témákban van, máshol nincs.
Ez tulajdonneveknél és német főneveknél is gondot okoz.
A kapitalizációt inkább a nyelvi fájl szintjén kéne kezelni, és nem a UI-kódban, ahol csak megoldható.

**Comment by RedyAu** [comment]
Why closed? Továbbra is rossz

**Comment by UnknownPlayer78** [comment]
hozzam assignoltad, engem viszont nem erdekel, szerintem jo igy ha valaki ugy erzi hogy ki szeretne javitani akkor ok

**Comment by UnknownPlayer78** [comment]
de szerintem nincs ra igeny

**Comment by RedyAu** [comment]
Erre lehet az összes capitalt replacelni: `{this[0].toUpperCase()}${this.substring(1)}`
Látsz-e vele potenciális hibát?

**Comment by RedyAu** [comment]
Szerintem megcsinálgatom devre

**Comment by UnknownPlayer78** [comment]
azert volt igy mert sokszor volt rossz a data

**Comment by UnknownPlayer78** [comment]
valahol mar nem emlekeszem hol es random uppercase volt a kozepen ahol nem kellett volna hogy legyen

**Comment by UnknownPlayer78** [comment]
meg emlekszem ra hogy volt ilyen azt hogy hol mar nem de azert keep in mind

**Comment by RedyAu** [comment]
Hát inkább legyen az, de legalább visszaadja azt, ahogy a tanár beírja. Most minden tulajdonnevet lezúz kicsire, ami nagyon hülyén néz ki (pl. tulajdonnévnél pl. irodalomból)

**Comment by RedyAu** [comment]
Hallod, én azt hittem ez egy beépített dart cucc, de csak a helperből kell kivenni egy .toLowerCase-t és kész
![image](https://user-images.githubusercontent.com/12989935/93018145-eb1f0180-f5cd-11ea-8a0e-78bc11a1bf72.png)

**Comment by RedyAu** [comment]
b7d7805
