### ISSUE TITLE
Órarendnél rossz a hetek számozása

### ISSUE THREAD

**Issue by stsmurfy** [filcnaplo/filcnaplo#18]
Helló! Az órarend megjelenítésénél nem jól írja ki a hetek számozását, emiatt pedig nem is lehet tovább lapozni, mert már az 53. hétnél jár.

![Screenshot_2020-08-31-19-26-32-461_hu filcnaplo ellenorzo](https://user-images.githubusercontent.com/25842875/91748479-56290b00-ebc0-11ea-90f1-64e9f923fd26.jpg)

**Comment by UnknownPlayer78** [comment]
Ez nagyon ritkan fordul elo, de azert javitom. Holnapra mar jonak kell lennie mert szept 1-tol szamolja a heteket.

**Comment by stsmurfy** [comment]
Még ma sem az igazi, ugyanis 0. hetet ír, és igaz, hogy a programozók 0 indexszel indítanak, de azért a köznyelvben ez inkább az 1. hét 😉

**Comment by UnknownPlayer78** [comment]
Valóban, de mivel eddig rendesen működött, azt gyanítom hogy ezt valami más okozza. (talán az hogy nincs hétfő de nem vagyok benne még biztos)
Következő frissítésre javítva lesz.

**Comment by UnknownPlayer78** [comment]
javítva
