### ISSUE TITLE
Kérdés

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#18]
Az lenne a kérdésem hogy megtudjátok-e oldani hogy az alkalmazáson belül lehessen frissíteni az appot.

**Comment by thegergo02** [comment]
Lehetséges lenne, de szerintem egy app store (mondjuk F-Droid release) és akkor nem kéne az appon belül frissíteni mivel az nem a legelegánsabb megoldás.

**Comment by RedyAu** [comment]
Igen, amint lehet, megoldjuk. Ez a terv.
