### ISSUE TITLE
Dark mode-ban az EvaluationCard-nál a név színe fekete

### ISSUE THREAD

**Issue by UnknownPlayer78** [filcnaplo/filcnaplo#19]

**Comment by RedyAu** [comment]
Ez a user beállított színétől függ, ami fekete. Az én hibám, mert alap belépésnél multimódban ragad. Nem volt időm kibogozni még, addig is állítsd át a színét a userednek.

**Comment by UnknownPlayer78** [comment]
Nem csinálok új issue-t ennek, de ha fehérre állítom akkor meg a SummaryCard színe rossz.

**Comment by RedyAu** [comment]
Állítsd szürkére XD
Nem, actually azt kéne csinálni, hogy mint a jegyek színeinél, a summary card is kiszámolja a szín alapján hogy a  címét fehéren vagy feketén írja ki.
