### ISSUE TITLE
Alkalmazás váltástól lefagy

### ISSUE THREAD

**Issue by gutyina70** [filcnaplo/filcnaplo#20]
Amikor megnyomom az alkalmazás váltás gombot, majd a filcre nyomok, akkor az applikáció teljesen lefagy. Csak az újra indítás oldja meg.

Nagyon valoszínű, hogy a rootolás miatt van, másoknál még nem hallottam ilyet.

Android verzió: 7.1.2
LinageOS verzió: 14.1-20191107-UNOFFICIAL-j3xnlte

**Comment by UnknownPlayer78** [comment]
Nem tudom mi okozhatja nálad, de nekem is egyedi problémának tűnik úgyhogy zárom.
