### ISSUE TITLE
Faliújság kártya

### ISSUE THREAD

**Issue by RedyAu** [filcnaplo/filcnaplo#20]
Régi designban maradt; nem reagál a témaváltásra. Kaphatná ugyanazt a designt mint az alatta látható "feljegyzés", csak más színnel és címmel.
![](https://i.imgur.com/Ynrvyra.jpg)![](https://i.imgur.com/jdisWqy.jpg)

**Comment by Ludvi01** [comment]
És nekem pont erre kellene egy némítás (ha van értesítésróla) és elrejtési lehetőség.

**Comment by RedyAu** [comment]
Kiteszik faliújságba és feljegyzésbe is? :D

**Comment by RedyAu** [comment]
Amúgy az a különbség asszem, hogy a feljegyzés csak egy tanulóé, a faliújság meg az egész osztálynak ugyanaz

**Comment by Ludvi01** [comment]
Igen ki is teszik mind a kettő helyre meg a heti rendszerességű szülőik is oda megy az értesítő. (autómatikus) és konkrétan senkit nem érdekel mert kb senki nem szokott elmenni.

**Comment by RedyAu** [comment]
https://github.com/filcnaplo/filcnaplo/commit/71edf6d01526f7f900391fc9dc3968a571a8fb3a
