### ISSUE TITLE
Nem engedi frissíteni az appot. 

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#21]
Valaki másnak is van ilyen gondja?
Mit lehet tenni hogy engedje? 
(a le törlésen kívül) 

![Screenshot_20200207-073904_Package installer](https://user-images.githubusercontent.com/46907508/74006810-1cbb5480-497d-11ea-901d-7085de9e288c.jpg)

**Comment by RedyAu** [comment]
Töröld le az előző installt. Ha nem akarsz újra bejelentkezni, a beállításokból exportáld a "users"-t, majd újratelepítés után a bejelentkezésnél importáld.

**Comment by Ludvi01** [comment]
Ezt a verziót én is tudtam. Csak azt hittem van más lehetőség is.

Kellene a fiókok exportálásával a beállításokat is exportálni.

**Comment by RedyAu** [comment]
@Unknown Ez lehet hogy azért rossz, mert más aláírás volt rajta?

**Comment by UnknownPlayer78** [comment]
Igen ez azért van

**Comment by RedyAu** [comment]
Akkor még a kövi is rossz lesz, aztán jó :P
