### ISSUE TITLE
Nem megbízható értesítések

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#24]
![20200210_094944](https://user-images.githubusercontent.com/46907508/74182732-e82cee80-4c43-11ea-8109-7bd59680ef7e.jpg)

**Comment by Ludvi01** [comment]
Itt most ki kellene vonom az 1 órából 55 percet??? 🤔🤣

**Comment by RedyAu** [comment]
Pontosan, az értesítések elég vacakul működnek, az első óráról az utolsó végekor értesít :P

**Comment by RedyAu** [comment]
#34 Csak második próbálkozásra kapcsolódnak be az értesítések.

**Comment by UnknownPlayer78** [comment]
duplicate
