### ISSUE TITLE
A "krétások" frissítették az API-t "v2"-es re, v1 nem működik

### ISSUE THREAD

**Issue by xsilent007** [filcnaplo/filcnaplo#25]
Néhány dolog amit megfejtettem eddig:
- Tanulói adatok lekérdezésének végpontja: `api/v1/StudentAmi`
- Már a bejelentkezéskor van a kérésben egy `Authorization` header

**Comment by xsilent007** [comment]
Update:

- Órák lekérdezésének végpontja: `/api/v1/LessonsAmi`

**Comment by xsilent007** [comment]
Update: a bejelentkezésnél valószínűleg csak egy bug miatt van Authorization header, lehetséges, hogy false alert.

Valamint ahogy elnézem annyi a "v2", hogy minden végpont végére odaraktak egy `Ami`-t

**Comment by xsilent007** [comment]
De ezt tesztelni kell még

**Comment by RedyAu** [comment]
Ez újdonság, hogy a v1-et lezárták? Eddig mindkettő működött.
Az AMI ugyanolyan mint a nem AMI amennyire tudom v1 és v2 alatt is, csak annyi hogy az AMI minden suliban működik, a nem AMI meg az AMI-kban (alapfokú művészetoktatási intézmény) nem. Ez az utolsó csak tipp, de az AMI cucc akkor kezdődött, amikor megcsinálták a zeneiskolás modult a krétához.

**Comment by RedyAu** [comment]
A Filc (legalábbis nálam) jelen formájában tökéletesen működik, ezt zárom.

**Comment by xsilent007** [comment]
Nekem a hivatalos Kréta `Ami`s végpontokat használ mindenre, a Filcben a bejelentkezés se működik.

**Comment by xsilent007** [comment]
Megpróbálok utánajárni ennek a dolognak és ha találok fixet, dobok egy PR-t, csak Dartot nem használtam még egyáltalán.

**Comment by xsilent007** [comment]
Addig meg reopenelem az issuet

**Comment by RedyAu** [comment]
Láttam próbáltad :D

**Comment by UnknownPlayer78** [comment]
@xsilent007 dologozol még ezen?

**Comment by UnknownPlayer78** [comment]
Egyenlőre bezárom, ha találnál valamit nyugodtan nyisd újra.

**Comment by xsilent007** [comment]
Mivel C#-ban vagyok a legjáratosabb, megpróbálok egy wrapper csinálni benne. Aztán ha találok hasznos infót megosztom veletek. :grinning:

**Comment by leventea** [comment]
@xsilent007 egy kicsit lassú a srác nem baj

**Comment by xsilent007** [comment]
@UnknownPlayer78 @RedyAu Szóval, sikerült gyorsan egy API Wrappert csinálnom C#-ban, nekem a bejelentkezés tökéletesen működik (mert még csak azt csináltam meg :P) [Link](https://github.com/xsilent007/KretaSharp)

**Comment by thegergo02** [comment]
Ha jól emlékszem csak bizonyos iskolákkal nem megy.

**Comment by palmarci** [comment]
igazából mit csinál másképp?
amugy ha c#, akkor https://github.com/palmarci/eKRETA-decompiled

**Comment by xsilent007** [comment]
Ötletem sincs, mit csinál a Filc másképp, de az fix, hogy a Filccel nem működik a bejelentkezés, a wrapperemmel pedig igen (attól függetlenül hogy ugyanazt a kérést küldik 🤔)

Esetleg valaki megpróbálhatja a wrapperemet a saját adataival ha működik a Filc neki. (A Constants.cs file gitignoreban van, nem fogja leakelni az adataidat a git 😉)

**Comment by xsilent007** [comment]
@palmarci szerintem szedd le, mert jogilag nem helyes... nehogy valami gondjaid adódjanak

**Comment by palmarci** [comment]
leg kevésbé sem izgatnak a krétások jogi dolgia, mellesleg idáig is kint volt

**Comment by palmarci** [comment]
@xsilent007 lehet hogy tudnál kuldeni HttpCanaryvel és wiresharkkal logot hogy össze tudjuk hasonlítani a kettot?

**Comment by xsilent007** [comment]
A token request amit a wrapperem küldd: ```
POST https://xxxxxxxx.e-kreta.hu/idp/api/v1/Token HTTP/1.1
Host: xxxxxxxx.e-kreta.hu
User-Agent: Kreta.Ellenorzo/2.9.9.2020022101 (Android; &#@!)
Content-Type: application/x-www-form-urlencoded
Content-Length: 191

institute_code=xxxxxxxx&userName=yyyyyyyyyyy&password=zzzzzzzzzzzzzzzzzzz&grant_type=password&client_id=919e0c1c-76a2-4646-a2fb-7085bbbf3c56```

És a Student request: ```
GET https://xxxxxxxxx.e-kreta.hu/mapi/api/v1/StudentAmi HTTP/1.1
Host: xxxxxxxxx.e-kreta.hu
User-Agent: Kreta.Ellenorzo/2.9.9.2020022101 (Android; &#@!)
Authorization: bearer yyyyyyyyyyyyyy```

**Comment by xsilent007** [comment]
Viszont a Filc nem is küld semmit 🤔🤔![HttpCanary](http://fos.hu/q2j)

**Comment by 3niXboi** [comment]
@xsilent007 Én nem veszek részt a Filc fejlesztésében de írtam egy [új API dokumentációt](https://documenter.getpostman.com/view/10379752/SzKPULz6) Postman-ben. Ami ott szerepel, az garantált, hogy működik.
 * Ha jól értem, C#-ban dolgozol, ha a nyelvet átállítod rá (amennyiben RestSharp-ot használsz) egy az egyben ki tudod másolni a dokumentációból a lekéréseket
 * A run in postman gombbal le tudod futtatni a kéréseket postman-ből és tudod tesztelni, hogy mi működik és mi nem

Remélem tudtam segíteni

**Comment by xsilent007** [comment]
Köszi a dokumentációt! Nem tudtam miért `null` az átlagok 😁. Nem használok semmi mást a mezei `HttpClient`-en felül, mivel csak extra overhead. Összesen ennyit (ez is csak egy `struct` és allokáció mentes😄) használok: https://github.com/xsilent007/KretaSharp/tree/master/KretaSharp/Internal/Request.cs
