### ISSUE TITLE
Bemutatás

### ISSUE THREAD

**Issue by werymanen** [filcnaplo/filcnaplo#25]
Szerintem egy bemutatás a naplóba jól jönne, ami körbemutat az alkalmazáson.

Megmutathatná egyes menüpontok helyét, hogyan lehet beállításokba belépni, stb...

**Comment by daaniiieel** [comment]
Ilyen már eddig is van első indításkor

**Comment by werymanen** [comment]
Umm, elég biztos vagyok benne hogy nekem nem volt.
Lehet hogy azért mert nem az első alkalmazásindításkor jelentkeztem be?

**Comment by UnknownPlayer78** [comment]
igen
