### ISSUE TITLE
Főképernyő

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#26]
A főoldalt a több felhasználós módban kicsit nagyobb a hely, mint ami kellene.

![20200211_114421](https://user-images.githubusercontent.com/46907508/74230070-e60a7480-4cc3-11ea-9dde-2712444dc789.jpg)

**Comment by RedyAu** [comment]
Nem adott a tanárod címet a dolgozatnak.

**Comment by RedyAu** [comment]
Ha ilyenkor nem lenne ott a sor hely, akkor nem ugyanolyanok lennének a kártyák, ami csúnya lenne. :/

**Comment by Ludvi01** [comment]
Jogos oké köszi
