### ISSUE TITLE
Hibás házi feladat megjelenés

### ISSUE THREAD

**Issue by stsmurfy** [filcnaplo/filcnaplo#26]
Ma jött egy házi feladat ami eléggé szét van esve Filcben. Esetleg valami ötlet?

![Screenshot_2020-09-07-19-18-29-613_hu.filcnaplo.ellenorzo.jpg](https://user-images.githubusercontent.com/25842875/92408998-78320880-f13f-11ea-8a76-c3962550abc2.jpg)

**Comment by UnknownPlayer78** [comment]
van valami ami null vagy nincs beirva
ez lehet hogy a tanar neve, tantargy neve stb
azzal tudnal segiteni ha megnezned kretaban hogy milyen adat hianyzik vagy ha kuldenel egy logcatet

**Comment by UnknownPlayer78** [comment]
valoszinuleg a tanar neve lesz az mert olyan mint ha a profilkepnel lenne valami baja

**Comment by stsmurfy** [comment]
> valoszinuleg a tanar neve lesz az mert olyan mint ha a profilkepnel lenne valami baja

Helló! Végre volt egy kis időm megnézni a nyers adatot. Íme:

```
  {
    "FeladasDatuma": "2020-09-07T09:36:45Z",
    "HataridoDatuma": "2020-09-13T22:00:00Z",
    "RogzitesIdopontja": "2020-09-07T09:36:45Z",
    "IsTanarRogzitette": true,
    "IsTanuloHaziFeladatEnabled": false,
    "IsMegoldva": false,
    "RogzitoTanarNeve": null,
    "Szoveg": "27 Eu countries and the 27 capital cities-fejből tudni",
    "TantargyNeve": "Európa-ismeret angol nyelven",
    "OsztalyCsoport": {
      "Uid": "814155"
    },
    "Uid": "521"
  },
```

Valóban a tanár neve lesz a hiba forrása.

**Comment by UnknownPlayer78** [comment]
>  "RogzitoTanarNeve": null,

pontosan

**Comment by UnknownPlayer78** [comment]
Ha a kovetkezo verzioban megjavul kerlek zard be

**Comment by stsmurfy** [comment]
Egy fokkal jobb, de még mindig nem nyert.
![Screenshot_2020-09-19-21-55-37-050_hu.filcnaplo.ellenorzo.jpg](https://user-images.githubusercontent.com/25842875/93688019-ecb36280-fac2-11ea-8a1b-1a7cba0f1dcc.jpg)

**Comment by UnknownPlayer78** [comment]
Nem jobb csak nincs ott a kesz gomb

**Comment by UnknownPlayer78** [comment]
ez betabol van?

**Comment by stsmurfy** [comment]
Japp. 2.0.3. Most tettem fel.

**Comment by RedyAu** [comment]
@stsmurfy Ez hogy áll?

**Comment by stsmurfy** [comment]
> @stsmurfy Ez hogy áll?

Most megnéztem. Ahogy látom szépen javítva lett. Lezárható.
