### ISSUE TITLE
Kezdő oldal beállítása 

### ISSUE THREAD

**Issue by Levminer** [filcnaplo/filcnaplo#27]
Ha megnyitom a filcet ugye alapbol a keresés oldalra dob be, de jó lenne egy opció hogy ki lehessen választani hova dobjon be pl. a tervezőhöz.

**Comment by UnknownPlayer78** [comment]
Mindig azon a tabon nyilik meg a tabon belul amelyiken hagytad. Ezt a beallitast nem szeretnenk ennel tovabb bonyolitani.

**Comment by Levminer** [comment]
Hát nekem nem, de rendben .+1 nyomás csak

**Comment by RedyAu** [comment]
Hamarosan érkezik @Zoldszemesostoros jóvoltából a beállításokba egy opció, amivel kiválaszthatod, melyik oldalon nyíljon meg az alkalmazás (ez a tabokra nem vonatkozik, az továbbra is a legutóbbi)

**Comment by UnknownPlayer78** [comment]
Elnezest kerek azt hittem arra gondolsz hogy be lehessen allitani hogy a lapon belul melyik tabot nyissa meg. Szoval amit mondtam nem volt helytelen, mivel tenyleg megjegyzi hogy melyik tab van megnyitva a lapon belul. Amikor megnyitottad az issuet mar dolgoztunk egy ilyen funkcion, sot, githubon mar ki is volt adva ezert eloszor nem ertettem a kerest.

**Comment by Levminer** [comment]
Igen frissitettem reggel és ott az opcio köszi.

**Comment by RedyAu** [comment]
2.0.2
