### ISSUE TITLE
Fiók importálása után bezár az app

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#27]
1. Fiók(ok) Importála után bezár az app és utána meg is nyílhatna.

2. Boa-nak már írtam, de itt is leírom. Kellene egy 45perces szinkron is ami iskola időben óra végén szinkronizál egyet.

3. A következő óra értesítés adatai nem tudnak frissülni? 
- az app megnyitása után törölhetné. 
- a régebbi értesítést törölhetné (ha lehet)

**Comment by thegergo02** [comment]
A 2. pontosan minek?

**Comment by Ludvi01** [comment]
Miért tán nem? Én pl 15 percesen használom jelenleg. De ekkora nem kellene de az 1 óra meg már sok.

**Comment by RedyAu** [comment]
Egyszeri értesítés törölni, utólag módosítani nem tudunk. Ehhez állandó értesítés kéne, de az meg pl. nem jelenne meg okosórákon.

**Comment by RedyAu** [comment]
Sajnos az importálás utáni bezárás megoldása nehezen kivitelezhető, nem ér annyit a megoldása, amennyi időbe telne.
