### ISSUE TITLE
Új felhasználó hozzáadásánál csak újranyitás után tölti be az adatokat

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#28]
Egyfolytában hibát ír és nem akar rendesen szinkronizálni.

Fiók váltáskor fekete kijelző és semmi reakció. 

Frissíteni még mindig nem lehetett az appot csak törölve.

**Comment by UnknownPlayer78** [comment]
Elméletileg ez volt az utolsó alkalom, hogy nem lehetett frissíteni törlés nélkül, ez után jónak kell lennie.

A többiről nem tudok mondani semmit, de tudunk a problémákról, ha lesz időnk javítjuk.

**Comment by Ludvi01** [comment]
Oké köszi.

**Comment by Ludvi01** [comment]
Nem működik a ha kapnék egy... - kész gombja.

**Comment by RedyAu** [comment]
Új fiók hozzáadása után jelenleg be kell zárni az appot, és a következő nyitásnál tölti be megbízhatóan az új felhasználó adatait.
A szinkronizáció rate-limitelt, 5 percenként csak egyszer ad lehetőséget az app, ezét tűnhet úgy hogy nem szinkronizál; nem is teszi.
Ha hibát ír, az majdnem biztosan kréta hiba, tegnap este is volt kimaradás náluk.

**Comment by RedyAu** [comment]
A kész gombot köszi, hogy mondod, javítjuk.

**Comment by RedyAu** [comment]
@Ludvi01 Kérlek ezután hibánként nyiss issuet, és a címében írd le röviden a hibát.

**Comment by Ludvi01** [comment]
Oké megpróbálom. 😉

**Comment by Ludvi01** [comment]
@RedyAu nem új fiókról beszélek én épp most hanem meglévőről. Az egész app befagy amit át állítom egy másik fiókra.

**Comment by RedyAu** [comment]
Ez jelentkezik másnál? Én nem tapasztaltam.
