### ISSUE TITLE
FilcNapló 5let

### ISSUE THREAD

**Issue by TheAquaWolf** [filcnaplo/filcnaplo#28]
Épp azon gondolkoztam hogy tök jó hogy van alkalmazás, de mi lenne ha lenne webrendszere is. Pl: filcnaplo.hu/bejelentezes vagy login.filcnaplo.hu cím alatt lehetne weben is látni a jegyeket. Tudom van a kréta...... de hát a nem a legjobb.

**Comment by RedyAu** [comment]
Egyelőre biztosan maradunk az alkalmazás fejlesztésénél, készültek már jó kréta webkliensek, keress csak rá. Ezt így zárom.
