### ISSUE TITLE
Egy óra 3x jelenik meg

### ISSUE THREAD

**Issue by Levminer** [filcnaplo/filcnaplo#29]
A krétában normálisan jelenik meg szoval a filc hibája szerintem.

![Screenshot_20200910-092221.png](https://user-images.githubusercontent.com/33373714/92695420-b6e6df00-f348-11ea-9ea0-288ab22a12f8.png)

**Comment by UnknownPlayer78** [comment]
Ilyen csak akkor történik amikor nincs internet?

**Comment by Levminer** [comment]
Ráfrissitettem mobilnettel szoval gondolom igen.

**Comment by UnknownPlayer78** [comment]
Hogy lehet replikalni?

**Comment by Levminer** [comment]
Nem volt internet és így töltött be, nem sikerult megismételnem most.

**Comment by UnknownPlayer78** [comment]
jo lenne rendesen megoldani de egyelore annyit csinalok hogy az azonos idju orakat torlom mivel nem tudok rajonni mi okozza
