### ISSUE TITLE
Okos User-Agent nem működik

### ISSUE THREAD

**Issue by stsmurfy** [filcnaplo/filcnaplo#3]
Gondolom ez még csak fejlesztés alatt van, de jelezném, hogy ha be van kapcsolva az "Egy felhasználó a főoldalon" opció, akkor az Okos User-Agentre kattintva kikapcsolja az egy felhasználó módot.

**Comment by palmarci** [comment]
javitottam

**Comment by palmarci** [comment]
mégse

**Comment by palmarci** [comment]
mégis
