### ISSUE TITLE
Szülői fióknál a szülő, nem a gyerek nevét mutatja

### ISSUE THREAD

**Issue by RedyAu** [filcnaplo/filcnaplo#33]
> ⭐⭐⭐⭐⭐
> Sokkal jobb volt, nem tetszik. Több gyereknél nem lehet tudni, melyik profilban vagyunk. A szülő nevét mutatja.A szinek bénák, a betük a neveknél fölösleges, nem lehet átírni. Stb.stb.

Renáta Barta, Google Play

**Comment by stsmurfy** [comment]
Az egyedi szín megadása valóban fájóan hiányzik, de a nevet át lehet írni, szóval vmi elkerülte a figyelmét. Így, hogy négy fiók van beállítva nekem Filcben könnyebb lenne ha saját magam adhatnám meg a nekem megszokott színeket.
