### ISSUE TITLE
Rate limit rakjon ki egy Toastot, amikor megtagadja a frissítést

### ISSUE THREAD

**Issue by RedyAu** [filcnaplo/filcnaplo#33]
Jelenleg kicsit olyan, mintha bug miatt hagyná abba a frissítést, semmi infót nem ad.
Toast tartalmazhatná, hány perc múlva lehet újra frissíteni.

**Comment by UnknownPlayer78** [comment]
Szerintem a toast nem lenne a legjobb megoldás, de majd gondolkozom rajta.

**Comment by RedyAu** [comment]
Igazából az összes toastot le kéne cserélni a material designos alsó feljövő cuccra, akármi is annak a neve...

**Comment by RedyAu** [comment]
Snackbar! Nagyon kreatív :D

**Comment by UnknownPlayer78** [comment]
jó ötlet

**Comment by UnknownPlayer78** [comment]
abban viszont már benne vagyok

**Comment by RedyAu** [comment]
https://github.com/filcnaplo/filcnaplo/commit/ee85fe0c9613001ea7949cdec85f6381e8ea0632

**Comment by RedyAu** [comment]
Egyelőre marad toast, majd cseréljük a többivel együtt snackre
