### ISSUE TITLE
Az értesítések nehézkesen engedélyezhetőek

### ISSUE THREAD

**Issue by Zoldszemesostoros** [filcnaplo/filcnaplo#34]
Az android alapú huawei telefonon (9.1.0) az értesítések engedélyezéséhez (az alkalmazàs menüjében) a beállításokban ki-be kell kapcsolni az értesítések engedélyezését, enélkül a "Nem sikerült engedélyezni az értesítéseket" üzenetet kapom.

**Comment by UnknownPlayer78** [comment]
Tudunk a problémáról viszont fogalmunk sincs hogy mi okozhatja.

**Comment by RedyAu** [comment]
Próbálom az open issue-kat kezelhető számban tartani :P
