### ISSUE TITLE
A beállítások-->infó menüpont nem mindig működik

### ISSUE THREAD

**Issue by Zoldszemesostoros** [filcnaplo/filcnaplo#37]
Az információk helyett 10 - 15 db "invalid argument(s)" üzenetet kapok, új sorral és vízszintes vonallal elválasztva, piros háttérrel. Néha meg gond nélkül megy.

off: Azért nem irigyellek titeket... Bezárjátok egy issue-mat délelőtt, nyitom az újat délután. :D

**Comment by RedyAu** [comment]
Nem gond, meg zárom is, mert az a képernyő meg fog szűnni jelen formájában.
