### ISSUE TITLE
New LessonCard

### ISSUE THREAD

**Issue by RedyAu** [filcnaplo/filcnaplo#45]
Ez a "következő óra" kártya, az órarend és a házik kezelésének újragondolása, melynek tervét a tanév eleje óta dédelgetem magamban. Most úgy érzem, meg tudom csinálni, de ez majd elválik...
 - [x] Ez a terv
 - [x] UI terv
 - [x] Backend terv
 - [x] Backend funkciók tesztelése, kipróbálása
 - [x] Frontend alap
 - [x] Frontend szép dizájn
 - [x] onTap lessonDialog
 - [ ] mai órarend link
 - [x] x db házi van ma
 - [ ] Header: mai dátum, mai hét napja

To Be Continued...

**Comment by RedyAu** [comment]
![image](https://user-images.githubusercontent.com/12989935/74602402-5cceb580-50a8-11ea-860b-3ec58d802bbb.png)

**Comment by RedyAu** [comment]
Backend terv:
 - [ ] Óra alatt / Szünetben vagyunk?
 - [ ] Előző óra class megszerezni
 - [ ] Jelen óra class megszerezni
 - [ ] Következő óra class megszerezni
 - [ ] Előző és következő szünet hosszának kiszámolása
 - [x] Hátralevő idő számolása a következő óráig
 - [ ] Widget class készítése az óralistához
 - [ ] Házi hozzáadása dialog revamp (more info later)

**Comment by RedyAu** [comment]
Óra-Tile
![image](https://user-images.githubusercontent.com/12989935/74605811-bdbbb500-50cb-11ea-80e9-8857b5a8b146.png)

**Comment by RedyAu** [comment]
Kártyadesign további tennivalók
 - [ ] Felső időkártya legyen accentColor jelenleginél
 - [ ] Felső időkártya legyen kevésbé szaturált accentColor előzőnél, következőnél
 - [ ] Óraszám írjon +-t konzis óránál
 - [ ] Óraszám legyen nagyobb
 - [ ] Óranevek kezdődjenek nagy betűvel
 - [ ] Ház ikon padding
 - [ ] trailing jobbra és középre rendezés
 - [ ] Előző és következő kártya háttere szürke
 - [ ] Jelenlegi kártya háttere kevésbé szaturált accentColor

**Comment by Ludvi01** [comment]
Helló. Figyelj a házi hozzáadásánál, mert egyes sulikban ez a funkció le van tiltva! (diákoknál)

**Comment by Kristof120701** [comment]
Én olyat képzelnék el esetleg, hogy a házikat helyileg tárolja, ne töltse fel a Kréta szerverére.

**Comment by RedyAu** [comment]
Igen, a távoli jövőben jó lenne egy olyan opció, hogy valamit csak magának mentsen el az ember.

**Comment by UnknownPlayer78** [comment]
kész
