### ISSUE TITLE
Fő képernyő nem tölt be semmit (nagyon sok idő után jelent meg)

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#48]

**Comment by UnknownPlayer78** [comment]
Ezzel a hibával még nem találkoztunk. Le tudod írni hogy mi történik pontosan?

**Comment by Ludvi01** [comment]
Mostmár van, nagyon sok idő után jelent meg.

**Comment by UnknownPlayer78** [comment]
a nagyon sok idő az elvileg az első órád alatti idő

**Comment by UnknownPlayer78** [comment]
javítva
