### ISSUE TITLE
Szöveges jegyek támogatása

### ISSUE THREAD

**Issue by AThokay** [filcnaplo/filcnaplo#48]
A jegyek fülön ha a gyerek százalékosan kapja az értékelést, akkor a 3 jegyű számok, pl 100% helyett csak a 10 jelenik meg. Nehogy emiatt kapjon ki a gyerek.
![filc](https://user-images.githubusercontent.com/72131611/94669858-1c0f6e00-0312-11eb-9497-cf6458eb5ea6.png)

**Comment by UnknownPlayer78** [comment]
ilyet meg nem lattam

**Comment by AThokay** [comment]
Az "is" jelölésnél az érték "Jól megfelelt". Az annyira nem zavaró, mint a százalékos lerövidítése.

**Comment by UnknownPlayer78** [comment]
az "is" ismeretlen lenne csak azt is levagja

**Comment by RedyAu** [comment]
- Százalék kicsit kisebb betűvel, hogy elférjen a `100`
 - A számérték alá `%`
 - Szöveges értékelésnél pl. `feather` ikon, a jegykártyán a szöveges értékelés első sora kiemelve megjelenítve

Így, vagy akár máshogy megoldva szívesen látunk PR-t bárkitől, akár részleteiben is. ;)

**Comment by RedyAu** [comment]
Százalékos jegyek javítva (#64), szöveges jegynél `is` helyett `?` kijelzése (nem végleges)

**Comment by UnknownPlayer78** [comment]
ez kesz?

**Comment by stsmurfy** [comment]
> ez kesz?
> 

Ez kész.
