### ISSUE TITLE
Felhasználói információk nem tölt be felhasználó váltás után. 

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#49]
Ez lehet a főképernyő nem betöltése miatt?

Amikor felhasználó váltás után rányomok az ℹ️ jelre akkor egy teljesen fehér képernyőt kapok.

**Comment by Ludvi01** [comment]
És a fő képernyőről nem frissül váltáskor.

**Comment by Kristof120701** [comment]
Én amikor ma megnyitottam az appot (egyfelhasználósan használom), minden előzmény nélkül én is ezt kaptam. Kényszerleállítás után sem működik. 

![Screenshot_2020-02-18-09-01-47-162_hu filcnaplo ellenorzo](https://user-images.githubusercontent.com/54689523/74715928-d643e080-522d-11ea-9652-f90c14a45202.jpg)

**Comment by UnknownPlayer78** [comment]
Az első órán jelenleg egy bug miatt nem tölt be a főképernyő, következő frissítésben javítva lesz
