### ISSUE TITLE
Levélírásnál nem látszódó szóközök

### ISSUE THREAD

**Issue by DCM-senpai** [filcnaplo/filcnaplo#5]
Ha a szöveg közepébe írsz valamit, akkor a szóközök csak akkor látszódnak ha utánaírsz valamilyen más karaktert

[screen.zip](https://github.com/filcnaplo/filcnaplo/files/4972063/screen.zip)

**Comment by pepyta** [comment]
Nekem nagyon úgy tűnik, hogy ez a billentyűzeted tulajdonsága. Próbáltad más alkalmazás `Textarea`jában használni?

**Comment by DCM-senpai** [comment]
Más alkalmazás textareajába nem tapasztaltam hasonló hibát, viszont regenerálni tudtam emulátorba.

**Comment by UnknownPlayer78** [comment]
Egyedi hibanak latszik ugyhogy zarom
