### ISSUE TITLE
Holnapi nap

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#50]
![20200217_103900](https://user-images.githubusercontent.com/46907508/74641510-b64ee700-5171-11ea-8bd0-a9bf45acd0b0.jpg)
Nem rossz, de még azért nem kellene mutassa hogy holnap mennyi óra lesz.
Az szerintem a 7/8/9. Óra után jelenjen max meg.

**Comment by Zoldszemesostoros** [comment]
Miért, mi baj van azzal, ha rögtön látom a holnapi órák számát?
Egy felirat viszont nem ártana, ami kiírja, hogy ma meddig tart még a szenvedés :smile: .

**Comment by Ludvi01** [comment]
Hát mondjuk az hogy annyira nap közben nem érdekel a holnapi nap, ha viszont szükség lenne rá akkor meg meglehet nézni. 

Az se rossz csak azzal mindig is "gond" volt.

**Comment by UnknownPlayer78** [comment]
Következő update-ben kicsit máshogy lesznek az órákkal kapcsolatos kártyák úgyhogy ez meg lesz oldva

**Comment by RedyAu** [comment]
A holnapi órakárya hiba miatt marad ott végig, az ki fog onnan kerülni. Nap-folyamatjelzőt is tervezek.
