### ISSUE TITLE
Nem lehet üzenetek kijelölni

### ISSUE THREAD

**Issue by Bazsi122** [filcnaplo/filcnaplo#50]
amikor egy tanár küld üzenetet az egész osztálynak akkor az abba beágyazott linkeket nem lehet megnyitni csak egyszerűen egy nyomással és az üzenet szövegét sem lehet kimásolni. Ha hosszan nyomom a szöveget akkor nem jelöli ki a szöveget mint más alkalmazásokban és nem lehet megnyitni linket.

**Comment by RedyAu** [comment]
#46
