### ISSUE TITLE
Információk és verziószám

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#51]
Miért nincs sehol megjelölve hogy milyen verzió számú az app?

**Comment by UnknownPlayer78** [comment]
Az alkalmazás beállításainál ott van, de később lesz normális about screen valahol.
![Screenshot_20200217_135254](https://user-images.githubusercontent.com/55922348/74655633-f8395680-518c-11ea-8154-710748b206da.jpg)

**Comment by Ludvi01** [comment]
Kösz... És KIA fene mászik oda be?

**Comment by RedyAu** [comment]
Az about screen újra lesz írva, de azzal egyetértek, hogy a verziót mutassa a globalDrawerben. Nem zavart ott senkit.

**Comment by palmarci** [comment]
fixeltem tegnap
