### ISSUE TITLE
Ötlet (vigyázz hosszú!) 

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#52]
A beállításokba kellene egy olyan opció amiben a felmentett tantárgyak ki be kapcsolási opció lenne.

Pl: ha valaki sikeresen teljesíti előrehozottam az informatikát, angolt, magyart, matekot,... Akkor azt ki tudja kapcsolni. Amivel nem jön róla értesítés, nem jelenik meg az órarendben meg sehol.

**Comment by UnknownPlayer78** [comment]
Sajnos nem értem mire gondolsz, esetleg kifejthetnéd bővebben.

**Comment by Ludvi01** [comment]
@UnknownPlayer78 minek zárogatsz le mindent???

**Comment by UnknownPlayer78** [comment]
Ezeket az órákat az iskola kezeli, nem a filc, így az ő feladatuk, hogy ezeket az órákat kivegyék tőled. Nekünk ilyen funkcióra nincs igényünk úgyhogy kérlek fordulj hozzájuk.

**Comment by Ludvi01** [comment]
Miután az órákat be írják akkor tűnik el.
Csak akkor is idegesítő látvány hogy ott van, de mégsem...
A hozzáállásod és stílusod nem jön be!

**Comment by RedyAu** [comment]
Köszönjük a visszajelzéseidet, de meg kell értened, hogy kb. 3-an próbáljuk ezt a projektet életben tartani.
Sok szempont érvényesül a fejlesztésre jutó időben, többek között fontossági sorrend és motiváció is. Sajnos saját ötletből is van elég, ezeket nyilván szívesebben írja meg az ember.
Ha valamit nagyon szeretnél látni, akár te is megpróbálhatod belekódolni, vagy szólhatsz ismerősödnek, aki ért ehhez.
Mi is csak önkéntesen, saját örömünkre csináljuk a fejlesztést, nem várhatsz mást.

Kérlek ezzeket tartsd észben amikor issuet nyitsz hibajelentéssel vagy ötlettel.

**Comment by Ludvi01** [comment]
Oké... Boának mégis sikerült csomó én általam javasolt dolgot bele vinni.
Értem én ti 3-an vagytok boa egyedül volt...

Megértem hogy van más is én csak egy ötletet írtam amit nem a kövi updateba várok nyilván hanem majd "évek múlva".

Nyilván sok sikert kívánok.
