### ISSUE TITLE
A főképernyő mostmár csak rá frissítésre frissül csak. 

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#53]
Eddig a név legalább meg változott.
És ki írogatja hogy 5 perc múlva frissíthetek csak (ez minek kellett?)

**Comment by Zoldszemesostoros** [comment]
Lásd: #33

**Comment by UnknownPlayer78** [comment]
Eddig is csak 5 percenként frissült csak nem szólt amikor nem firssíthettél.

**Comment by Ludvi01** [comment]
Az a kérdés hogy minek? És miért zárogatod le? Nincs megoldva mert a fő kérdésre nem jött válasz!

**Comment by thegergo02** [comment]
Mivel a krétának nem tetszett a sok lekérés (valószínüleg)
