### ISSUE TITLE
Manuálisan kell megnézni hogy van-e frissités.

### ISSUE THREAD

**Issue by ChickenSenpai777** [filcnaplo/filcnaplo#54]
Szerintem a beállitások menüben lehetne egy frissitések keresése és egy weboldal megnyitása gomb. Nagyon más problémát nem találtam már igy is jobb mint a kréta!

**Comment by rocketbucket10** [comment]
Ez a funkció már benne van a alkalmazásban. (b1.2+)

**Comment by ChickenSenpai777** [comment]
Akkor nem jelzett az b1.3 frissitésről ezekszerint.

**Comment by RedyAu** [comment]
Azért nem, mert @palmarci még mindig nem frissítette a settings.jsont... Pls do it already.
