### ISSUE TITLE
Statisztika oldal elrendezés

### ISSUE THREAD

**Issue by Kristof120701** [filcnaplo/filcnaplo#55]
Eléggé zavaró, hogy most visszafelé vannak rendezve a jegyek a tantárgyaknál, a plusz gomb miatt. Nem lehetne esetleg a gombot áttenni valamilyen másik részre? (esetleg oda ahol a szivacsban is volt)

**Comment by UnknownPlayer78** [comment]
Miért zavar hogy visszafelé vannak a jegyek? Az összes jegy nézetnél is időrrendben vannak a jegyek.

**Comment by UnknownPlayer78** [comment]
Ha az a problémád, hogy amikor átváltasz statisztika nézetre akkor lentre van görgetve?

**Comment by Kristof120701** [comment]
Igen, inkább az, hogy visszafelé kell görgetni.

**Comment by RedyAu** [comment]
Következő update.

**Comment by UnknownPlayer78** [comment]
pls már megcsináltam

**Comment by RedyAu** [comment]
Öhm nem volt megcsinálva, de mostmár actually megcsináltam :DD Felül kezdődik a lista a legfrissebb elemekkel.
