### ISSUE TITLE
Faliújság személyre szabhatóság

### ISSUE THREAD

**Issue by cicomk** [filcnaplo/filcnaplo#56]
Szia!
Néha túl hosszú üzeneteket küldenek a diákoknak a faliújságra, ami meg jelenik a kezdőlapon is. Jó lenne egy olyan opció, amin keresztül ki lehet kapcsolni az üzenetek megjelenítését a kezdőlepon.

**Comment by UnknownPlayer78** [comment]
A következő frissítésben a kezdőoldalon csak 4 sor jelenik meg a faliújság tartalmából.

**Comment by RedyAu** [comment]
Hogy kitaláltad előre :D
