### ISSUE TITLE
Betölt, de mégsem tölt be.

### ISSUE THREAD

**Issue by throwaway73720** [filcnaplo/filcnaplo#58]
Ez a probléma akkor kezdett el történni mikor b1.3 ra frissítettem.

Az app megnyitása után csak egy szürke/fehér képernyöt mutat, de viszont az 1. óra után már jól jelenik meg minden.

**Comment by UnknownPlayer78** [comment]
Tudunk a problémáról, következő frissítésben javítva lesz.
