### ISSUE TITLE
Értesítések

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#59]

**Comment by UnknownPlayer78** [comment]
Valóban, de azt eddig is tudtuk hogy az éretsítések nem működnek

**Comment by Ludvi01** [comment]
Azért van záró jelben mert nekem még ment előző verzióban. Már ahogy nyilván.

**Comment by UnknownPlayer78** [comment]
### eFILC Infornatikai Zrt
Tisztelt felhasználó!Kérjük a jelzett probléma megoldása érdekében vegye fel velünk a kapcsolatot e-mailben az ugyfelszolgalat@efilc.hu címen, ahol megírja pontosan mi a hibajelenség, milyen készülék és melyik verziójú operációs rendszere, melyik verziójú alkalmazás esetén tapasztalja a hibát.

**Comment by palmarci** [comment]
Már van egy ilyen issue, most látom
