### ISSUE TITLE
Statisztikák / átlag design

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#60]
Jegyek / eredmények:
- Szerintem: 1 2 3 4 5 sorrendben kellene írni nem úgy ahogy most van (mondjuk ez nem annyira lényeges.)
- átlaggal kellene kezdeni valamit mert így nem néz ki valami szépen.

**Comment by Daaniiieel** [comment]
Eredmények: szerintem meg pont nem, időrendben sokkal jobb

Átlag: mi benne a csúnya?

Emlékeztető, egyenlőre egyébként egy stabil verzió az eddigi dolgokkal a cél

**Comment by UnknownPlayer78** [comment]
1. egyetértek, ha szeretnél jegyek szerint rendezni, lehet
2. valóban kéne valami szebb

**Comment by RedyAu** [comment]
Az átlagra van szebb ötletem, azt megcsinálom hamarosan. Ez most azért ilyen, mert jelen dizájn arra volt tervezve, hogy van módusz és medián is alatta.
A jegyek sorrendjénél az összes jegyszámot mutató kártyák sorrendjére gondolsz?

**Comment by RedyAu** [comment]
Következő update.
