### ISSUE TITLE
Beállítások / exportálás

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#61]
Az exportálás kiválasztásakor és vissza lépés után a beállítás kijelölése át ugrik a fő képernyőre úgy hogy a beállításokban vagy. 🙄

**Comment by UnknownPlayer78** [comment]
### eFILC Infornatikai Zrt
Tisztelt felhasználó!Kérjük a jelzett probléma megoldása érdekében vegye fel velünk a kapcsolatot e-mailben az ugyfelszolgalat@efilc.hu címen, ahol megírja pontosan mi a hibajelenség, milyen készülék és melyik verziójú operációs rendszere, melyik verziójú alkalmazás esetén tapasztalja a hibát.

**Comment by Ludvi01** [comment]
??? Minek?

**Comment by Ludvi01** [comment]
- nem is létezik... 
- amit írtam...
- Legújabb
- Samsung galaxy note 10 plus 
- Android 10
