### ISSUE TITLE
### eFILC Infornatikai Zrt

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#62]
### eFILC Infornatikai Zrt
Tisztelt felhasználó!Kérjük a jelzett probléma megoldása érdekében vegye fel velünk a kapcsolatot e-mailben az ugyfelszolgalat@efilc.hu címen, ahol megírja pontosan mi a hibajelenség, milyen készülék és melyik verziójú operációs rendszere, melyik verziójú alkalmazás esetén tapasztalja a hibát.

_Originally posted by @UnknownPlayer78 in https://github.com/filcnaplo/filcnaplo/issues/59#issuecomment-588127072_

**Comment by UnknownPlayer78** [comment]
### eFILC Infornatikai Zrt
Tisztelt felhasználó!Kérjük a jelzett probléma megoldása érdekében vegye fel velünk a kapcsolatot e-mailben az ugyfelszolgalat@efilc.hu címen, ahol megírja pontosan mi a hibajelenség, milyen készülék és melyik verziójú operációs rendszere, melyik verziójú alkalmazás esetén tapasztalja a hibát.

**Comment by Ludvi01** [comment]
Ez jó!
Kréta felé válasz de jó!
Ha valaki tudja hogy kell saját email szervert csinálni szóljon már.
