### ISSUE TITLE
Kontakt opció AboutScreenen

### ISSUE THREAD

**Issue by misiDEV** [filcnaplo/filcnaplo#63]
Sziasztok! 
Lenne pár ötletem az apphoz:
•Megosztás gomb, ami filcnaplo.hu-t osztja
•Kontakt opció az appban

**Comment by RedyAu** [comment]
Mindkettő be fog kerülni, amint lesz új AboutScreen.

**Comment by Levminer** [comment]
Nekem hiányzik a battle royale mód. A szivacs emlékére be kéne rakni azt is.

**Comment by RedyAu** [comment]
@Levminer Valószínűleg nem fog visszakerülni, a kréta random piszkálását Filc alatt nem folytatjuk.

**Comment by RedyAu** [comment]
Következő updateben bekerül egy hibajelentés gomb.

**Comment by Zoldszemesostoros** [comment]
Jó lenne a filcnaplo.hu - n is egy hibajelentés menüpont, amit github fiók nélkül is lehetne használni (ha lenne rá igény szerintetek is, megcsinálnám).
