### ISSUE TITLE
Oldal váltás után a főoldal nem mindig tölt be

### ISSUE THREAD

**Issue by CsakiTheOne** [filcnaplo/filcnaplo#64]
![Screenshot_20200221-074623](https://user-images.githubusercontent.com/26061759/75010888-9aec2080-547e-11ea-9b89-348cec720400.png)
![Screenshot_20200221-074630](https://user-images.githubusercontent.com/26061759/75010891-9b84b700-547e-11ea-8168-70e34b8247f6.png)
Az alkalmazás induláskor rendesen betöltődött, megnéztem az órarendem és utána vissza akartam lépni a főoldalra. Ott ez fogadott és nem tudtam frissíteni, újabb oldal váltás sem oldotta meg a problémát.

**Comment by UnknownPlayer78** [comment]
### eFILC Infornatikai Zrt
Tisztelt felhasználó!Kérjük a jelzett probléma megoldása érdekében vegye fel velünk a kapcsolatot e-mailben az ugyfelszolgalat@efilc.hu címen, ahol megírja pontosan mi a hibajelenség, milyen készülék és melyik verziójú operációs rendszere, melyik verziójú alkalmazás esetén tapasztalja a hibát.

(légy szíves nézd meg a closed issue-kat)
