### ISSUE TITLE
Multi-user támogatás

### ISSUE THREAD

**Issue by Daaniiieel** [filcnaplo/filcnaplo#65]
A cím önmagáért beszél.
Tudom, hogy ez nem feltétlen a legfontosabb, mert nincs GUI módja a felhasználó hozzáadásnak, de a bug attól még bug.

**Comment by palmarci** [comment]
A mutliuser tamogatast majd a jovobe igyekszunk megoldani.

**Comment by RedyAu** [comment]
Következő update.

**Comment by RedyAu** [comment]
Javítva.

**Comment by RedyAu** [comment]
https://github.com/filcnaplo/filcnaplo/commit/97c65c0c4ae4814254be4f8559f0b304dd0f9655
