### ISSUE TITLE
Üzenetek hiba

### ISSUE THREAD

**Issue by Kristof120701** [filcnaplo/filcnaplo#69]
Ha bárhogyan is szinkronizál az app, az üzenetek menü üres lesz. Ha még az előtt nézem meg, mielőtt leszinkronizál az app, akkor működik.

[Videó a hibáról](https://1drv.ms/v/s!AuogV6cJdTrlzx_c15ovdAJGeYJj)

**Comment by RedyAu** [comment]
A Kréta üzenetküldő rendszere jelenleg a hivatalos appban sem működik, valamit épp átalakítanak rajta.
A Filc a legutóbbi sikeres szinkron eredményét mutatja amíg le nem frissül hibásan, tehát a frissítés előtt látszó pár üzenetet még jóval korábban töltötte le.
Köszi a részletes hibajelentést.
