### ISSUE TITLE
Dark mode esetén navigációs sáv sötétítése

### ISSUE THREAD

**Issue by pepyta** [filcnaplo/filcnaplo#7]
A dark mode egy remek funkció, viszont akinek nem fizikai gombos telefonja van, azoknak ez a sáv mindig fehér marad, ami így egy eléggé igénytelen képet tud festeni.

**Hogyan lehetne javítani?**
A flutter tartalmaz erre gyári megoldást.
```dart
import 'package:flutter/services.dart';

SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
  systemNavigationBarColor: Colors.blue, // navigation bar color
  statusBarColor: Colors.pink, // status bar color
));
```

**Comment by daaniiieel** [comment]
Android 10, MI AI2 lite. Nem tudom reprodukálni.

**Comment by pepyta** [comment]
> Android 10, MI AI2 lite. Nem tudom reprodukálni.

Nincs véletlen bekapcsolva neked a System-wide dark mode?

**Comment by daaniiieel** [comment]
De, közben én is rájöttem, hogy az volt :)

**Comment by pepyta** [comment]
Az alkalmazás oldalán lehet "ráerőltetni" az Androidra, hogy használja azt a színt.

**Comment by RedyAu** [comment]
++, én is tapasztaltam ezt Samsung S8-on.
