### ISSUE TITLE
Nem kéri le az órarendet

### ISSUE THREAD

**Issue by cicomk** [filcnaplo/filcnaplo#71]
Nem kéri le novembertől az órarendet.

**Comment by stsmurfy** [comment]
Megírnád kérlek melyik verzióval próbálkoztál? Amennyiben nem a legfrissebbel ([2.0.4](https://github.com/filcnaplo/filcnaplo/releases/tag/2.0.4)), úgy kérlek frissítsd és próbáld meg újra.

**Comment by cicomk** [comment]
![Screenshot_2020-11-02-09-38-46-977_hu filcnaplo ellenorzo](https://user-images.githubusercontent.com/11236576/97847122-61e39b80-1cef-11eb-9991-b84e3ef151e8.jpg)

**Comment by UnknownPlayer78** [comment]
ebben meg nincs benne a fix, a playes 2.0.4-et nezd

**Comment by UnknownPlayer78** [comment]
tudom kicsit fura de axt akartuk hogy az orarend mukodjon ezert gyorsan kiadtuk playre

**Comment by cicomk** [comment]
Rendben, köszönöm!
Bár hiányozni fog a közelgő dolgozat/házi cuccos. Oda még a következő órát is kiírhatná.

**Comment by UnknownPlayer78** [comment]
Most meg vannak problemak a betas valtoztatasokkal de amint kijavitjuk, kiadjuk azokat a 2.0.5-ös verzioban.

**Comment by RedyAu** [comment]
Kicsit körmönfont módon, de ki fogjuk tudni adni a 2.0.5-beta0-át, az eddigi tesztfunkciókkal és működő órarenddel @cicomk
