### ISSUE TITLE
Házi hozzáadása nem menti el a sortöréseket

### ISSUE THREAD

**Issue by RedyAu** [filcnaplo/filcnaplo#72]
Valószínűleg valami HTML varázslat kell hozzá, a krétából feltöltött házik a szivacsban és krétában is sortöröttek, a szivacsból felöltött házik viszont nem.

**Comment by Protocolls** [comment]
A sortörés helyére "\n"- t lehet beilleszteni  állatlában ez jelöli.
(még nem próbáltam ilyen körülmények között)

**Comment by RedyAu** [comment]
@Protocolls Meg kéne nézni HttpCanaryval a különbséget

**Comment by Protocolls** [comment]
> @Protocolls Meg kéne nézni HttpCanaryval a különbséget

Json:

  {
		
		    "Uid": "65",
		
		    "Id": 65,
		
		    "TanuloNev": "Tánczos János",
		
		    "FeladasDatuma": "2020-02-28T18:21:12.31",
		
		    "FeladatSzovege": "ez egz teszt&lt;br/&gt;sort&#246;r&#233;ssel&lt;br/&gt;a&lt;br/&gt;s&lt;br/&gt;g&lt;br/&gt;d",
		
		    "RogzitoId": 647595,
		
		    "TanuloAltalTorolt": false,
		
		    "TanarAltalTorolt": false
		  
	}
"FeladatSzovege": "ez egz teszt&lt;br/&gt;sort&#246;r&#233;ssel&lt;br/&gt;a&lt;br/&gt;s&lt;br/&gt;g&lt;br/&gt;d"

elküldött szöveg:
ez egz teszt&lt;br/&gt;sort&#246;r&#233;ssel&lt;br/&gt;a&lt;br/&gt;s&lt;br/&gt;g&lt;br/&gt;d

alap szöveg:

ez egz teszt
sortöréssel
a
s
g
d

**Comment by RedyAu** [comment]
Köszi szépen! Ez a házi eredetileg Kréta appból lett feltöltve ugye?

**Comment by Protocolls** [comment]
> Köszi szépen! Ez a házi eredetileg Kréta appból lett feltöltve ugye?

igen

**Comment by UnknownPlayer78** [comment]
fixed
