### ISSUE TITLE
Nem tölt be a weboldal! (semmi válasz) 

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#74]

**Comment by Daaniiieel** [comment]
Works on my machine, a probléma az ön készülékében van.

**Comment by Ludvi01** [comment]
Ez nem olyan biztos @Daaniiieel. 3 eszköz 4 különböző böngészőn nem töltött be.

**Comment by palmarci** [comment]
lehet hogy nem volt bekapcsolva a wifid nem?

**Comment by Ludvi01** [comment]
Mindig megy a wifi és a mobilnet is!

**Comment by Ludvi01** [comment]
PC-n, laptopon, telón is néztem.

**Comment by Daaniiieel** [comment]
- a weboldalos issuet a weboldalos repóba

- már megy, nem?

**Comment by UnknownPlayer78** [comment]
igen megy köszönjük mindenkinek, neked is ludvi
