### ISSUE TITLE
A statisztában ha +-t adunk hozzá:

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#75]
![20200229_114413](https://user-images.githubusercontent.com/46907508/75607203-d036e500-5af4-11ea-82b1-fcab1f8075f0.jpg)

**Comment by Daaniiieel** [comment]
Ez mi akar lenni?

**Comment by Daaniiieel** [comment]
Bug report? Enhancement? Suggestion?

**Comment by Ludvi01** [comment]
Bug...

**Comment by UnknownPlayer78** [comment]
### eFILC Infornatikai Zrt
Tisztelt felhasználó!Kérjük a jelzett probléma megoldása érdekében vegye fel velünk a kapcsolatot e-mailben az ugyfelszolgalat@efilc.hu címen, ahol megírja pontosan mi a hibajelenség, milyen készülék és melyik verziójú operációs rendszere, melyik verziójú alkalmazás esetén tapasztalja a hibát.

**Comment by Ludvi01** [comment]
Állj 🚫 már le ezzel. Nem vicces és fölös.
Te tényleg ennyire unatkozol?

**Comment by UnknownPlayer78** [comment]
@Ludvi01 nemvicces
