### ISSUE TITLE
Házi feladatok törlése

### ISSUE THREAD

**Issue by LenSoft-Softwares** [filcnaplo/filcnaplo#76]
Amenniyben lehetséges, jó lenne, ha egy házi törlése után a részletező ablak eltűnne, illetve a házik listája lefrissülne.

**Comment by RedyAu** [comment]
@LenSoft-Softwares A házi törlés egyelőre egy kezdeti kísérlet csak, sokat fog fejlődni a következő updatere.

**Comment by LenSoft-Softwares** [comment]
Igen, gondoltam. Hajrá! 😀
