### ISSUE TITLE
Statisztika képernyőn nem jelenik meg minden jegy egy tárgyhoz

### ISSUE THREAD

**Issue by marvelgj** [filcnaplo/filcnaplo#77]
Az utoló frissítés idejét be lehetne tenni a menübe.
A jegyek -> összesnél érdemes lenne szerintem vissza tenni tantárgyankénti rendezést, akar alapértelmezetten.
A jegyek -> statisztikánál nem jelenik meg az összes jegy az adott tárgyhoz.

**Comment by thegergo02** [comment]
1: Éppen próbálunk minél kevesebb dolgot odatenni.
2: Egyetértek
3: Nekem jó.

**Comment by jaszaygabor** [comment]
1.: Értem, viszont vannak olyan esetek, mikor jó lenne tudni, hogy mikor frissült utóljára.
3.: 8 jegyet kaptam matekból (ebből kaptam a legtöbbet), ebből 3 mat ebben a félévben, 1. jegy, amit kiír, az  2019.10.02.-ei, 2. 2019.10.24., 3. 2020.01.21.

**Comment by RedyAu** [comment]
El tudod küldeni esetleg a "jegyek, minden más" exportodat, akár nekem személyesen? Ide ne posztold  ki mert, vannak benne (bőven) személyes adatok, viszont a jegy-nem-megjelenítés (3.) szinte biztos hogy valami helyi sajátosság miatt van, ahogy nálatok beírják a jegyeket, ezt enélkül nem tudjuk javítani. Ha gondolod, küldés előtt nézd át az exportot, és töröld belőle az érzékeny dolgokat.

**Comment by RedyAu** [comment]
Az 1.-höz pedig: A weboldalon láthatod a legutóbbi verziót, és hogy az mikor jött ki. Ha nem sír az alkalmazás, hogy frissítsd, akkor a legfrissebbed van. Ezekből össze lehet rakni a dolgot, nem látom ennek annyi hasznát, hogy felépítsük a funkcionalitást.

**Comment by jaszaygabor** [comment]
1.: Úgy értem, hogy mikor lett utóljára lekérdezve és letöltve az adat, nem a program, hogy mikor lett frissitve.
3.: Elküldöm

**Comment by RedyAu** [comment]
1: Ahá! Világos. Erről akár lehet szó, de minden oldal máskor kerül frissítésre, sokféle különböző lekérés megy a kréta szeverre, minden oldalra külön szöveg kéne hozzá. Szerintem a közeljövőben ne számíts rá.

**Comment by jaszaygabor** [comment]
Aham, és ha csak az lenne kiírva, amikor a főoldalt frissíti? Akkor mindent frissít nem?

**Comment by RedyAu** [comment]
@jaszaygabor Hát nem éppen mindent, de a nagyrészét igen. Tudsz mondani egy esetet, amikor ez hasznos lenne?

**Comment by jaszaygabor** [comment]
Pl, mikor tanár beír egy jegyet, de nálam nem jelenik meg több perc után sem, akkor jó lenne tudni, hogy csak nem hozta le, vagy nem is rögzítette. Nálunk sokszor volt ilyen, hogy nem jelent meg. Volt, hogy azért, mert nem vitte fel és volt olyan is, hogy csak nem hozta le.

**Comment by RedyAu** [comment]
@jaszaygabor Ha frissítesz, és nem írja ki hogy csak 1 percenként frissíthetsz, akkor biztos lehetsz benne, hogy frissített az app.

**Comment by palmarci** [comment]
egyébként off topic de ha matekbol jegyet kapunk akkor nekem az 2 nappal kesobb jelenik meg mint a tobbieknek és nem fogom fel hogy miért

**Comment by RedyAu** [comment]
@palmarci Mindig?

**Comment by palmarci** [comment]
igen, csak matek, csak annal a tanarnal

**Comment by jaszaygabor** [comment]
@RedyAu erre még nem gondoltam.

**Comment by UnknownPlayer78** [comment]
@jaszaygabor mem vagytok esetleg csoportbontásban matekból?

**Comment by marvelgj** [comment]
Nem, nem vagyunk

**Comment by marvelgj** [comment]
A többi tantárgynál is így hozza, a szivacsnál is és a krétálál is ezt csinalta/csinálja.

**Comment by thegergo02** [comment]
@marvelgj Ha a hivatalosban is rossz, nem a mi hibánk.

**Comment by marvelgj** [comment]
A statiszikát nem ti állítjátok össze a leszedett adatokból?

**Comment by marvelgj** [comment]
A kréta appnál jelenleg annyit látok a statisztikánál, hogy 9 jegyet kaptam, a valós 9 ből,
a filcnél ugyanezeket kihozza az összes jegynél, csak a statisztikánál nem, csak 3 mat

**Comment by marvelgj** [comment]
A kréta "értékelések"nél ugyanúgy kihozza a 9 et, plusz 1 félévi értékelést
