### ISSUE TITLE
Kártyák olvasottnak jelölése, egyedi színere lehetőség

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#8]
1. A fő képernyőről egy idő után vagy megtekintés után el tünhetne a félévi és év végéig jegyek.

2. A szineknél lehetne rgb szín keverő amit a felhasználó magának tud kikeverni, és mellette persze az alap színek.

3. Ha megoldható lenne akkor erre szeretnék kérni egy kikapcsolási lehetőséget. Mind értesítés mind megjelenésben. 
![Screenshot_20200202-001158](https://user-images.githubusercontent.com/46907508/73600465-a966ac80-4550-11ea-989f-5163139f7958.jpg)

**Comment by RedyAu** [comment]
1: Lehet róla szó, de akkor csinálni kell hozzá egy visszavonási lehetőséget a beállításokba
2: Ha a jegyek színére gondolsz, már most is van! Keresd a beállítások között.
3: Ezek mik? Feljegyzések? Üzenetek? Mit akarsz rajtuk kikapcsolni? Honnan fogja tudni a program hogy mikor van erről a fajta üzenetről szó?

**Comment by Ludvi01** [comment]
3. Hetente szokott jönni. 
![Screenshot_20200202-094034](https://user-images.githubusercontent.com/46907508/73605557-1a818080-45a0-11ea-8ca7-08ffbc4ab421.jpg)

**Comment by Ludvi01** [comment]
2. Az összes színre gondoltam (amik most is vannak)
Pl: ilyen típusú:
![20200202_094318](https://user-images.githubusercontent.com/46907508/73605600-8f54ba80-45a0-11ea-8443-0ccbd0640c62.jpg)
en típusú

**Comment by RedyAu** [comment]
2: Úgy érted, hogy ne csak a jegyek, de pl. a következő órák, feljegyzések, helyettesítések színét is át lehessen állítani?
3: Továbbra sem értem a problémát, sajnálom. Amennyire tudom, ezekről a Filc nem értesít, csak a jegyekről. Azzal pedig nem tudok mit csinálni, hogy a feljegyzések között ott vannak, az alkalmazás dolga az adatok megjelenítése, és ha ezt küldi a Kréta szerver, akkor megjelenítjük.
Arról esetleg lehet szó, hogy a főoldalon való megjelenítésüket kikapcsolhatóvá tegyem.

**Comment by Ludvi01** [comment]
2. nem úgy értem hogy ami eddig van az úgy is maradjon, csak legyen egy felhasználó által keverhető színskála. (de akár az is lehetne.)

3. még akár az is segítene.

UI: Csomó ötletet küldtem Boá-nak is, ugyhogy ha van akkor fogok küldeni, de nem itt akarnám. Privátban Telegram-mon.

**Comment by Ludvi01** [comment]
@RedyAu 1. Fiók(ok) Importála után bezár az app és utána meg is nyílhatna.

**Comment by UnknownPlayer78** [comment]
Mind a három kérés benne lesz a következű frissítésben valamilyen formában.

**Comment by RedyAu** [comment]
"következő"
