### ISSUE TITLE
ChooseLessonDialog TODO

### ISSUE THREAD

**Issue by RedyAu** [filcnaplo/filcnaplo#80]
- [x] I18n
 - [x] Dark mode
 - [x] Legutóbbi kiválasztása rádiógomb fix
 - [ ] Azonos tanár
 - [ ] Különböző nap

**Comment by UnknownPlayer78** [comment]
következő/előző ugyanilyen tantárgyú óra helyett következő/előző nem a ugyanazon a napon, ugyanazzal a tanárral lévő óra

**Comment by RedyAu** [comment]
Támogatom
