### ISSUE TITLE
Evaluations Screen nem jelenít meg súlyozás nélküli jegyeket (?)

### ISSUE THREAD

**Issue by Levminer** [filcnaplo/filcnaplo#82]
- [x] Ha elindul az első óra akkor az első órának a kártyája eltűnik és a második órának a kártyáját mutatja.
- [x] A jegyeknél támogatom a tárgyankénti rendezés visszarakását.
- [ ] Ha egy jegynek nincs beírva százalék (úgy írta be a tanár) akkor nem jelenik meg
- [x] (wontfix) A beállításokba a verziószámot érdemes lenne balra igazítani mert minden balra van igazítva.

**Comment by thegergo02** [comment]
1: Szerintem így kéne mennie, lehet félreértem.
2: Én is.
4: Jó ötlet

**Comment by Levminer** [comment]
@thegergo02 
2. az oké hogy eltűnik, de a többi óránál nem tűnik el, hanem mutatja hogy hány perc van az órából

**Comment by RedyAu** [comment]
1: Ha ez gond volt (most nem tudom ellenőrizni), javítva. Következő frissítés.
2: Ok, visszakerülhet.
3: Úgy érted, nincs súlyozva?
4: A többi gomb, ez csak infó, ezért van vizuálisan elválasztva a többitől. Szerintem maradjon így.

**Comment by RedyAu** [comment]
És @Levminer 1: Próbáltál visszafele lapozni?

**Comment by RedyAu** [comment]
2: Visszarakva.

**Comment by Levminer** [comment]
@RedyAu 
1. nem lehet visszalapozni, eltűnik.
3. igen nincs súlyozva, és így nem jelenik meg

**Comment by RedyAu** [comment]
@Levminer 1: Ok, javítva
3: Rendben.
Tanulság: Nyiss legközelebb külön issuekat ;)

**Comment by RedyAu** [comment]
@Levminer A kódot nézve szinte biztos vagyok benne, hogy nem a jegyek súlyozott voltával van a gond, hanem esetleg azzal, hogy nincsenek évközinek megjelölve. Ez sajnos a tanáraidtól függ, ez az oldal csak az évközieket mutatja.
Ha szeretnél még foglalkozni a dologgal, kérlek küldd el ide, vagy nekem személyesen emailben (fodor.benedek2001@gmail.com) a "jegyek, minden más" exportodat (személyes adataid nélkül).
Ha gondolod, újranyithatod a hibát ebben az esetben.

**Comment by Levminer** [comment]
@RedyAu Elküldtem, bár akkor te nem sok mindent tudsz vele kezdeni.
