### ISSUE TITLE
1 percenként egyszer frissíthetsz

### ISSUE THREAD

**Issue by Kristof120701** [filcnaplo/filcnaplo#83]
Sokszor olyan helyen írja ki ezt az alkalmazás amiről a felhasználó nem is tehet. (pl: órarend böngészésénél, amikor visszafele léptetem a hetet)

**Comment by UnknownPlayer78** [comment]
@Kristof120701 Jogos, következő frissítésben javítva lesz

**Comment by RedyAu** [comment]
Az órarend frissítésből kivettem a figyelmeztetést, ott úgyse frissít kézzel a user soha.
