### ISSUE TITLE
[BUG] [Jelezze, akinél előfordul!] Összecsúszó feljegyzés kártyák

### ISSUE THREAD

**Issue by marvelgj** [filcnaplo/filcnaplo#84]
Miért csinalja azt, mikor új jegyeket kapok (ahogy észrevettem többet kell kapjak, csak akkor), hogy összecsúszik 2 kártya a főoldalon és mikor lejjebb görgetek, ahelyett, hogy lehozná a régebbieket visszaugrik az elejére?
Viszont, ha utána újraindítom akkor jó.

**Comment by thegergo02** [comment]
@marvelgj Egyszer történt ilyen nekem, amikor valami jegyzet is ott volt.

**Comment by marvelgj** [comment]
Jah, nekem is azóta , mióta feljegyzést meg faliújságra is írtak

Üdvözlettel:
Jászay Gábor

Vári Gergő <notifications@github.com> ezt írta (időpont: 2020. márc. 3., Ke
16:31):

**Comment by Kristof120701** [comment]
Nekem pedig még a szivacsba fordult elő, amikor megjelentek a félévi jegyek, de miután újraindítottam az appot megjavult.

**Comment by RedyAu** [comment]
@marvelgj Színes főoldal beállításnál is jelentezik a hiba?

**Comment by marvelgj** [comment]
@RedyAu Azt nem tudom, nem próbáltam.

**Comment by RedyAu** [comment]
Valószínűleg az általunk használt alkalmazás-motor hibájából adódik a dolog, mivel újraindítástól megjavul. Az ilyen típusú hibáknál mi is csak reménykedni tudunk. A hibát egyelőre nyitva hagyom, ha bárki hasonlót tapasztal, jelezze. Ha sokaknál jelentkezik, lehet hogy kitalálunk rá valami megoldást.

**Comment by marvelgj** [comment]
Előjött ismét ez a hiba, csak most annyival módosult, hogy elég volt neki 1 faliújsági kiírás, és hiába nyitom meg újból az alkalmazást, frissítem le ugyanúgy megmarad a probléma annyival kiegészülve, hogy azt az 1 bejegyzést kiírja 10-15x is.

**Comment by thegergo02** [comment]
@marvelgj Nem kéne csekkolni a duplicate faliújságokra, feljegyzésekre? Nem kapnak valami egyedi ID-t?

**Comment by Kristof120701** [comment]
Nálam valamiért ez történt: https://1drv.ms/v/s!AuogV6cJdTrlzys6XHTbXL19Hs2k
És sötét módba pedig ez (Csak lefele görgettem és visszapattan, miután leszinkronizált, különben nem. Plusz van amikor egymásra rak 2 widgetet.) : https://1drv.ms/v/s!AuogV6cJdTrlzyyJZnMxNfDmA8a0

**Comment by marvelgj** [comment]
@thegergo02 Kivételesen most nekem nem tették ki faliújságra is, de szöveg eggyezőségre lehetne ellenőrizni.

@Kristof120701 Pontosan ugyanez nálam is.

**Comment by throwaway73720** [comment]
Az összecsúszás probléma nálam is előjött:
![Screenshot_2020-03-13-07-03-26-1](https://user-images.githubusercontent.com/61225245/76594529-b1275280-64f9-11ea-9746-da22234d4281.jpg)

**Comment by Zoldszemesostoros** [comment]
Ha a sok koronavírus kártya felett vannak jegyek, és ráfrissítek úgy, hogy nics internet, akkor a koronavírus alatt minden eltűnik, ha legörgetek, visszapattan a tetejére. Az újranyitás megoldja a problémát.

**Comment by marvelgj** [comment]
Jah, kiveve a sokszorozódást

**Comment by RedyAu** [comment]
Mostanában nem tapasztalta senki, ahogy látom. Valószínűleg Flutter frissítéssel javulhatott, nem mi voltunk :P
