### ISSUE TITLE
Mentse az app, melyik felhasználó van kiválasztva

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#9]
Nem frissül az óra rend!
Az appból való kilépéskor és újra belépéskor nem tartja meg hogy melyik fiókban zártam be.

**Comment by RedyAu** [comment]
Nem tudom, mit tapasztaltál az órarend frissítésénél, nálam userváltásnál rögtön frissül, és a másikét mutatja.
Viszont az igaz, hogy nem tartja meg a kiválasztott usert.
Remélem @palmarci -nak ez ujjgyakorlat ;)

**Comment by palmarci** [comment]
de vá én se értek ehhez az egészhez

**Comment by RedyAu** [comment]
Mostmár van valami fogalmam a mentésről, megpróbálhatom.

**Comment by Daaniiieel** [comment]
thegergo02 ezt te megoldod, vagy csináljam esetleg én

(Szerintem kb ez a szint amit én is tudok)

**Comment by Daaniiieel** [comment]
Nálam nem
