### ISSUE TITLE
[Feature Request] screenshot

### ISSUE THREAD

**Issue by botiapa** [filcnaplo/filcnaplo#92]
Szerintem egy-két screenshot jót tenne a reponak és a weblapnak egyaránt.

Emellett mivel a szivacs az egyik leghíresebb napló, egy összehasonlítás szerintem nem ártana.

**Comment by palmarci** [comment]
a weboldalon van screenshot

**Comment by botiapa** [comment]
Igaz, bocsi csak mobil módban nem látszódik. Erre is jöhetne egy fix.

**Comment by UnknownPlayer78** [comment]
@botiapa a mobil módban direkt nem látszik de megcsinálhatom

**Comment by botiapa** [comment]
@UnknownPlayer78 Köszi a gyors válaszokat. Egyértelmű, hogy nem nagy prioritású ez a probléma, de azért szerintem jobb lenne ha látszodna szerintem. Ha gondolod nyomhatok egy PR-t ha nincs időd rá.

**Comment by RedyAu** [comment]
@botiapa Ha esetleg járatos vagy Java-ban, C#/++-ban vagy hasonló nyelvben, szerintem mindenképp nézz rá akár az alkalmazás kódjára is :) Minden segítség jól jön.

**Comment by RedyAu** [comment]
Actually nem a playről szólt ez az issue. Nem akarsz egy galériát akár a nem-play sima screenshotokból a webre?

**Comment by botiapa** [comment]
Bocsi ez a kérdés hozzám szólt? @RedyAu
