### ISSUE TITLE
[BUG] ??????

### ISSUE THREAD

**Issue by throwaway73720** [filcnaplo/filcnaplo#94]
Ennek a "feljegyzés"nek csak egyszer kellene megjelenni, de valamiért megjelent kb 15ször.
![Screenshot_2020-03-12-07-38-21-1](https://user-images.githubusercontent.com/61225245/76504028-2b4acf00-6447-11ea-9a07-7f53aea239c8.png)

**Comment by throwaway73720** [comment]
A krétás appba jöl jelenik meg: 
![Screenshot_2020-03-12-09-56-06-1](https://user-images.githubusercontent.com/61225245/76504370-e5dad180-6447-11ea-9ade-fec9f30409b6.png)

**Comment by Daaniiieel** [comment]
Nem bug. Az api így adja le.

**Comment by Daaniiieel** [comment]
Mármint bug, de nem nagyon tudunk ellene tenni, mivel nem a mi oldalunkon ban a hiba.

**Comment by UnknownPlayer78** [comment]
Ha megnézed a kréta webes felületén, biztos vagyok benne hogy ott is meg fogod találni mind a 15-öt.

**Comment by throwaway73720** [comment]
Oké, ebben igazad van, de még azt nem értem hogy a szöveg miért nem jelenik meg úgy ahogy kellene: 
![Screenshot_2020-03-12-10-44-38-1](https://user-images.githubusercontent.com/61225245/76508364-8b913f00-644e-11ea-8d24-e54d13b26f51.png)
![Screenshot_2020-03-12-10-41-31-1](https://user-images.githubusercontent.com/61225245/76508298-6f8d9d80-644e-11ea-901b-5bc53989cb0a.png)

**Comment by UnknownPlayer78** [comment]
na azt én sem

**Comment by RedyAu** [comment]
@throwaway73720 Ezen mi a gond?

**Comment by throwaway73720** [comment]
Az üzenet eleje a közepén van, így kellene kezdődnie: 
![Screenshot_2020-03-12-10-48-40-1](https://user-images.githubusercontent.com/61225245/76508697-1d00b100-644f-11ea-9d38-a44d03a652a2.png)
