### ISSUE TITLE
[BUG] Nincs limitelve a legtobb helyen a szoveg

### ISSUE THREAD

**Issue by Ludvi01** [filcnaplo/filcnaplo#99]
![Screenshot_20200327-072920](https://user-images.githubusercontent.com/46907508/77728456-d5f0ef00-6ffc-11ea-876f-a4c694d3bb9f.jpg)

**Comment by Ludvi01** [comment]
![Screenshot_20200327-081958](https://user-images.githubusercontent.com/46907508/77731735-c923c980-7003-11ea-9c7d-e851d7b6705b.jpg)

**Comment by thegergo02** [comment]
@Ludvi01 Ngl az iskolád baromi hülyén használja a krétát, oda a tanár neve kéne. Mindegy, bekéne állítani egy karakter limitet aztán kiírni hogy …

**Comment by UnknownPlayer78** [comment]
fixed
